### ISSUE TITLE
SVM.py

### ISSUE THREAD

**Issue by antiDigest** [wadhwasahil/ML-bucket#1]
Hi,

I was looking at the code you have in your files. It's all running on libraries. Would you like to implement stuff ? I would like to contribute. Else, I can make a repo for self implementations and we can perform unit testing and implementations of all possible algorithms in machine learning.

**Comment by wadhwasahil** [comment]
Why would you like to do that? Aren't these libraries self sufficient?

**Comment by antiDigest** [comment]
Yes. Libraries are at the beck and call, but self implementation gives you the research confidence, which is good at applications of those algorithms. (You don't have to be dominated by how it is implemented in the library -- Self implementation is always better for learning)

Though sometimes it is possible that the library function performs much faster than your implementation. That is good for an implementer as you will know a way to make your code(s) run faster.

**Comment by wadhwasahil** [comment]
You can contribute in this repository itself instead of starting it from scratch.

**Comment by antiDigest** [comment]
Cool.

And why the hell do you have two github accounts ?
